#!/bin/sh
#
# Copyleft, AOSC Development Hub and the Core developers behalf.
#
# Purpose of this script:
# 1. Adjustment for current system.
# 2. News and issues to be read and advised by the users.
#
